version: "3.1"

services:
  time_estimates_web:
    container_name: time_estimates_web
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/var/www/html:cached
